// REDUX ACTION TYPES

export const USER_LOGOUT = "USER_LOGOUT"
export const USER_LOGIN = "USER_LOGIN"
export const USER_UPDATE_REDUX = "USER_UPDATE_REDUX"

export const GET_USER_INFO = "GET_USER_INFO"
export const GET_USER_INFO_REQUEST = "GET_USER_INFO_REQUEST"
export const GET_USER_INFO_REQUEST_FAIL = "GET_USER_INFO_REQUEST_FAIL"
export const GET_USER_INFO_REQUEST_SUCCESS = "GET_USER_INFO_REQUEST_SUCCESS"









export const LOGIN_OTP_REQUEST_SEND = "LOGIN_OTP_SEND_REQUEST_FAIL";
export const LOGIN_OTP_REQUEST_FAIL = "LOGIN_OTP_SEND_REQUEST_FAIL";
export const LOGIN_OTP_REQUEST_SUCCESS = "LOGIN_OTP_SEND_REQUEST_FAIL";






export const SELECT_CAR_TYPE = "SELECT_CAR_TYPE"
export const SELECT_CAR_RENTAL_ITEM = "SELECT_CAR_RENTAL_ITEM"
export const SELECT_CAR_TYPE_FAIL = "SELECT_CAR_TYPE_FAIL"
export const CLEAR_CAR_RENTAL_REQUEST_DATA_START = "CLEAR_CAR_RENTAL_REQUEST_DATA_START"




// GET CAR TYPE LIST
export const CAR_TYPE_REQUEST_SEND = "CAR_TYPE_REQUEST_SEND"
export const CAR_TYPE_REQUEST_SUCCESS = "CAR_TYPE_REQUEST_SUCCESS"
export const CAR_TYPE_REQUEST_FAIL = "CAR_TYPE_REQUEST_FAIL"




// GET CAR TYPE LIST
export const HOME_DATA_REQUEST_SEND = "HOME_DATA_REQUEST_SEND"
export const HOME_DATA_REQUEST_SUCCESS = "HOME_DATA_REQUEST_SUCCESS"
export const HOME_DATA_REQUEST_FAIL = "HOME_DATA_REQUEST_FAIL"





// GET RIDE LIST
export const RIDE_LIST_REQUEST_SEND = "RIDE_LIST_REQUEST_SEND"
export const RIDE_LIST_REQUEST_SUCCESS = "RIDE_LIST_REQUEST_SUCCESS"
export const RIDE_LIST_REQUEST_FAIL = "RIDE_LIST_REQUEST_FAIL"
export const RIDE_LIST_REQUEST_TYPE_CHANGE = "RIDE_LIST_REQUEST_TYPE_CHANGE"


// GET RIDE BIDDING LIST
export const RIDE_BIDDING_LIST_REQUEST_SEND = "RIDE_BIDDING_LIST_REQUEST_SEND"
export const RIDE_BIDDING_LIST_REQUEST_SUCCESS = "RIDE_BIDDING_LIST_REQUEST_SUCCESS"
export const RIDE_BIDDING_LIST_REQUEST_FAIL = "RIDE_BIDDING_LIST_REQUEST_FAIL"





// GET RIDE BIDDING LIST
export const SOCKET_REQUEST_SEND = "SOCKET_REQUEST_SEND"
export const SOCKET_REQUEST_SUCCESS = "SOCKET_REQUEST_SUCCESS"
export const SOCKET_REQUEST_FAIL = "RIDE_BIDDING_LSOCKET_REQUEST_FAILIST_REQUEST_FAIL"